#!/bin/bash

USERNAME=$(git config --global user.name)
TICKET_PREFIX=$(git config --global jira.prefix)

if [ "z${USERNAME}" == "z" ]
then
    echo "please set git user.name: git config --global user.name <USERNAME>"
    exit 1
fi

if [ "z${TICKET_PREFIX}" == "z" ]
then
    echo "please set ticket prefix: git config --global jira.prefix <PREFIX>"
    exit 1
fi




TICKET="${TICKET_PREFIX}-${1}"
SUMMARY=$(jira show ${TICKET} | grep -e "^.*│.*Summary.*│" | awk -F"│" '{print $3}')
SUMMARY=$(echo ${SUMMARY} | awk '{$1=$1};1' | tr '[:upper:]' '[:lower:]' | tr ' /\:' '_')
SUMMARY=${SUMMARY:0:40}


if [ "z${SUMMARY}" == "z" ]
then
    echo "no such ticket, aborting..."
    exit 1
fi

BRANCH_NAME="${TICKET}_${SUMMARY}_${USERNAME}"
FROM_BRANCH=${2}

git rev-parse --verify ${BRANCH_NAME} > /dev/null 2>&1

if [ $? -ne 0 ]
then
    CURRENT_BRANCH=$(git symbolic-ref HEAD | sed 's!refs\/heads\/!!')
    if [ ${CURRENT_BRANCH} != "dev" ] 
    then
        while true; do
            read -p "you are not basing of dev branch, are you sure? " yn
            case $yn in
                [Yy]* ) 
                    break;;
                [Nn]* ) echo "aborting..."; exit 1;;
                * ) echo "Please answer yes or no.";;
            esac
        done
    else
        echo "brining dev up to speed..."
        git pull
    fi

    git checkout -b ${BRANCH_NAME} ${FROM_BRANCH}
    exit 1
else
    git checkout ${BRANCH_NAME}
fi


if [ $? -ne 0 ]
then
    echo "failed switching to branch ${BRANCH_NAME}, aborting..."
    exit 1
fi

jira start ${TICKET}
