#!/bin/bash

USER=$1
TICKET_PREFIX=$(git config --global jira.prefix)
USERS_FILE=~/.gitlab_users

if [ "z${TICKET_PREFIX}" == "z" ]
then
    echo "please set ticket prefix: git config --global jira.prefix <PREFIX>"
    exit 1
fi

if [ "z${USER}" == "z" ]
then
    echo "usage: git review <username>"
    exit 1
fi


IFS=$'\n'
USERS=($(cat $USERS_FILE))

if [[ ! " ${USERS[@]} " =~ " ${USER} " ]]; then
    echo "User ${USER} doesn't exists, available users:"
    echo "${USERS[@]}" | tr " " "\n"
    echo "(if it's a new user, add it to $USERS_FILE and try again)"
    exit 1
fi

CURRENT_BRANCH=$(git symbolic-ref HEAD | sed 's!refs\/heads\/!!')
CURRENT_TICKET=$(echo ${CURRENT_BRANCH} | cut -d_ -f1)

if [[ ! $CURRENT_BRANCH == ${TICKET_PREFIX}* ]]
then
    echo "must be working on a ticket to issue review request"
    exit 1
fi

if [[ ${CURRENT_TICKET} != ${TICKET_PREFIX}* ]]
then
    echo "must be working on a ticket to issue review request"
    exit 1
fi

git diff-index --quiet HEAD --

if [ $? != 0 ]
then
    while true; do
    read -p "you have some uncommited work, are you sure you want to request code review? " yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) echo "aborting..."; exit 1;;
        * ) echo "Please answer yes or no.";;
    esac
    done
fi

git diff @{u} > /dev/null 2>&1

if [ $? != 0 ]
then
    echo "did you forget to push your branch? run:"
    echo "git push -u origin ${CURRENT_BRANCH}"
    exit 1
fi

lab mr -v -t dev -a ${USER}
jira review ${CURRENT_TICKET}
