#!/bin/bash

USERS_FILE=~/.jira_users

if ! [ -e $USERS_FILE ]
then
    JIRA_USERS=$(jira users | grep @ | cut -d│ -f2 | awk '{$1=$1};1')

    for u in $JIRA_USERS
    do
        echo $u >> ~/.jira_users
    done
fi

IFS=$'\n'
USERS=($(cat $USERS_FILE))

echo "${USERS[@]}" | tr " " "\n"
